### PR TITLE
compressive strength of concrete

### LINKED ISSUE #2: Simple Linear Regression Using Sci-kit learn
Add a simple linear regression model using sci-kit learn library.

## Steps to follow
Comment about your interest in the issue and the dataset you want to work with
Tell us your approach in brief
Let the mentor respond to you and only after that get started with the issue.
Don't forget to check the already existing model in order to know the structure.

Join the discussion channel here - [eduAlgo Community](https://edualgo-python-community.tribe.so/)
Let's have a chat at the community tab before starting contributions.

### PR DESCRIPTION
**Pull request by nitya123-github**
predicting compressive strength of concrete using machine learning algorithms such as Linear regression,
Lasso regression, Ridge regression, Decision Trees,Random Forests,

### CODE REVIEW

**Comment by Abhijit2505** [comment]
@all-contributors please add @nitya123-github for code

**Comment by Abhijit2505** [comment]
@all-contributors please add @nitya123-github for code

**Comment by nitya123-github** [comment]
thanks a lot!

**Comment by nitya123-github** [comment]
Is this counted for dwoc and how do i know its counted?

**Pull request merged**
