### PR TITLE
KNN implementation

### LINKED ISSUE #60: Implementation of KNN from Scratch without scikitlearn
Hii! Understanding ML algorithms from scratch is really significant while studying ML. I can add Implementation of KNN without using libraries, with proper comments for user to understand easily.

Kindly assign me this issue with label DWOC and Level- 4 or 5.

### PR DESCRIPTION
**Pull request by Rishikeshrajrxl**
Here I have implemented the KNN Machine Learning model with scikit-learn.
I have used the Dataset from Kaggle.

issues #8

### CODE REVIEW

**Comment by Rishikeshrajrxl** [comment]
@Abhijit2505, please review this PR

**Comment by Rishikeshrajrxl** [comment]
Please @Abhijit2505 , look to the matter as soon as possible.

**Comment by Abhijit2505** [comment]
> Please @Abhijit2505 , look to the matter as soon as possible.

Please add the documentation for your model as well.

**Comment by Rishikeshrajrxl** [comment]
@Abhijit2505   added the Documentation, kindly review.

**Comment by Rishikeshrajrxl** [comment]
Hey, @Abhijit2505 kindly review this PR, and let me know if changes required

**Pull request merged**
